@HostAddress = http://localhost:3000

### Send approval request to BPM api
GET {{HostAddress}}/bpm/api/approval-request?taskId=20709b48-8002-484d-b3d7-e47c7d7c23f6&userId=1
Content-Type: application/json
Accept: application/json

### Send approval request to BPM api (Failed scenario)
GET {{HostAddress}}/bpm/api/approval-request?taskId=e81f0a11-a62b-4f0e-9bdf-285663861035&userId=2
Content-Type: application/json
Accept: application/json

### Start UiPath Job - POST request
POST {{HostAddress}}/ui-path/api/start-job?taskId=e81f0a11-a62b-4f0e-9bdf-285663861035
Content-Type: application/json
Accept: application/json

### Get UiPath Job Status - GET request
GET {{HostAddress}}/ui-path/api/job-status?uiPathJobId=515655b1-cefe-4b1c-819b-d7d32be935e9
Accept: application/json

### Update Job Status to In-Progress
POST {{HostAddress}}/ui-path/api/update-job-status
Content-Type: application/json

{
  "uiPathJobId": "515655b1-cefe-4b1c-819b-d7d32be935e9",
  "newStatus": "In-Progress"
}

### Update Job Status to Ended
POST {{HostAddress}}/ui-path/api/update-job-status
Content-Type: application/json

{
  "uiPathJobId": "6961252a-c7c2-48ba-bfab-168a8ed4476b",
  "newStatus": "Ended"
}