@HostAddress = http://localhost:5283

### Send approved approval request response
POST {{HostAddress}}/api/webhook
Content-Type: application/json
Accept: application/json

{
  "TaskId": "738ff776-4170-428a-b81e-5ac2ce660360",
  "ApprovalStatus": "Approved"
}

### Send rejected approval request response
POST {{HostAddress}}/api/webhook
Content-Type: application/json
Accept: application/json

{
  "TaskId": "dbac2777-8bd8-447c-bf23-e939ad5e03f5",
  "ApprovalStatus": "Rejected"
}