@HostAddress = http://localhost:5283

### Send approved approval request response
POST {{HostAddress}}/api/webhook
Content-Type: application/json
Accept: application/json

{
  "TaskId": "f6ce2bcb-3566-4ba6-baaf-ce8844db0829",
  "ApprovalStatus": "Approved"
}

### Send rejected approval request response
POST {{HostAddress}}/api/webhook
Content-Type: application/json
Accept: application/json

{
  "TaskId": "dbac2777-8bd8-447c-bf23-e939ad5e03f5",
  "ApprovalStatus": "Rejected"
}