@HostAddress = http://localhost:5283

### Get All Workflows (Search for workflows)
GET {{HostAddress}}/api/workflows?terms=&status=0&type=&skip=0&take=100&createdFrom=2024-12-02

### Get a Single Workflow by ID
GET {{HostAddress}}/api/workflows/8f780f2b-3cef-4199-be10-855d5bb31c2f

### Start a Workflow (Post with data)
POST {{HostAddress}}/api/workflows/EmployeeTransferWorkflow
Content-Type: application/json
Accept: application/json

{"UserId": 1, "NewBranch": "Branch B"}

### Suspend a workflow (PUT)
PUT {{HostAddress}}/api/workflows/12345/suspend
Accept: application/json
Content-Type: application/json

### Resume a workflow (PUT)
PUT {{HostAddress}}/api/workflows/12345/resume
Accept: application/json
Content-Type: application/json

### Terminate a workflow (DELETE)
DELETE {{HostAddress}}/api/workflows/12345
Accept: application/json
Content-Type: application/json