@HostAddress = http://localhost:5283

### Send approved request
POST {{HostAddress}}/api/webhook
Content-Type: application/json
Accept: application/json

{
  "TaskId": "7e5ab446-de46-4f41-8281-40e63df6dc64",
  "ApprovalStatus": "Approved"
}

### Send rejected request
POST {{HostAddress}}/api/webhook
Content-Type: application/json
Accept: application/json

{
  "TaskId": "0f668980-d631-4bbc-8f7b-929f73362d52",
  "ApprovalStatus": "Rejected"
}