@HostAddress = http://localhost:5283

### Send approved request
POST {{HostAddress}}/api/webhook
Content-Type: application/json
Accept: application/json

{
  "TaskId": "071c4bf2-619f-4eb5-862a-f053dc859765",
  "ApprovalStatus": "Approved"
}

### Send rejected request
POST {{HostAddress}}/api/webhook
Content-Type: application/json
Accept: application/json

{
  "TaskId": "0f668980-d631-4bbc-8f7b-929f73362d52",
  "ApprovalStatus": "Rejected"
}